# Generated by Django 4.1.3 on 2022-12-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runphis', '0002_perfilnk'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=300)),
                ('passwordi', models.CharField(max_length=300)),
                ('codigo', models.CharField(max_length=300)),
            ],
        ),
    ]
